import { neutralColors } from "../Styles";

const SidebarStyle = {
  navContainer: {
    position: "absolute",
    top: "0",
    left: "0",
    height: "100%",
    width: "min(10%, 80px)",
    display: "flex",
    flexDirection: "column",
    backgroundColor: neutralColors.lightBlack,
    boxShadow: `0px 0px 10px ${neutralColors.lightBlack50}`,
    backdropFilter: "blur(20px)",
    padding: "5px",
    zIndex: "1",
  },
  navHeader: {
    height: "5%",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  navBody: {
    height: "90%",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "start",
  },
  navFooter: {
    height: "5%",
    width: "100%",
  },
  contextContainer: {
    position: "absolute",
    top: "5%",
    left: "min(10%, 80px)",
    height: "95%",
    width: "max(20%, 300px)",
    opacity: "1",
    transition: "left 0.5s",
    transitionTimingFunction: "ease",
    borderRadius: "0px 10px 10px 0px",
    backgroundColor: neutralColors.lightBlack50,
    boxShadow: `0px 0px 5px ${neutralColors.lightBlack25}`,
    backdropFilter: "blur(20px)",
    padding: "5px",
  },
  contextHeader: {
    height: "5%",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "start",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  contextBody: {
    height: "95%",
    width: "100%",
    marginTop: "5px",
    padding: "10px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "10px",
  },
  contextFooter: {
    height: "0%",
    width: "100%",
    marginTop: "5px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  toggle: {
    pointerEvents: "all",
    cursor: "pointer",
    display: "flex",
    width: "50px",
    minWidth: "20px",
    height: "50px",
    minHeight: "20px",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    borderRadius: "50%",
    backgroundColor: neutralColors.darkGray75,
    color: neutralColors.offWhite,
    fontSize: "16px",
    transform: "rotate(0deg)",
    transition: "transform 0.5s",
    transitionTimingFunction: "ease",
  },
  contextHeadIcon: {
    width: "10%",
    height: "100%",
    backgroundColor: "none",
    //backgroundImage: "url(icons/Layers.png)",
    backgroundSize: "contain",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
  },
  contextHeadTitle: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "start",
    color: neutralColors.offWhite,
    fontSize: "18px",
    fontWeight: "600",
  },
};

export default SidebarStyle;
